"""The blind grader's own contracts (no browser, no Kimi): rubric blindness, workspace hygiene,
seeded reel order, JSON robustness, response validation, and the pass rule on fixture scores."""
from __future__ import annotations

import json
import os

import numpy as np
import pandas as pd
import pytest

from animacy.grade import kimi, rubric
from animacy.grade.movements import (HELDOUT_PATH, HELDOUT_SET, MOVEMENT_KEYS, MOVEMENTS, TUNING_SET, VENDOR, ClipSpec,
                                     accepts_intent, candidate_table, load_heldout_movements, parse_variant, shared_phrases)
from animacy.grade.probe import PROBE_PROMPT
from animacy.grade.reel import (chunk_reels, number_and_shuffle, plan_reels, sealed_manifest, slow_audio, slow_table,
                                speech_envelope)
from animacy.grade.render import resample_table, urdf_frames
from animacy.grade.run import CALIBRATION_MIN, GATE_THRESHOLD, calibration, check_workspace, consistency, gate, \
    acquire_run_lock, contamination_gap, critiques, intent_resolution, judge_workspace_root, pid_alive, release_run_lock, prepare_workspace, redact_lines, resolve_gate_source, summarise, unseal
from animacy.profile import find_robot

REQUIRED_FORBIDDEN = {"animacy", "model", "retrieval", "generated", "vendor"}


# ---------------------------------------------------------------- rubric blindness
def test_forbidden_list_covers_the_required_words():
    assert REQUIRED_FORBIDDEN <= set(rubric.FORBIDDEN)


@pytest.mark.parametrize("robot", ["lamp", "reachy_mini", "some_new_robot"])
@pytest.mark.parametrize("strip", [True, False])
def test_rubric_prompt_has_no_project_context(robot, strip):
    prompt = rubric.build_prompt("C:/tmp/ws/reel.mp4", list(range(13, 25)), robot, has_speech_strip=strip)
    assert rubric.forbidden_hits(prompt) == []
    for w in REQUIRED_FORBIDDEN:
        assert w not in prompt.lower()
    assert "Clip" in prompt and "13" in prompt and "24" in prompt
    for k in rubric.SCORE_KEYS:
        assert k in prompt


def test_probe_prompt_and_card_lines_have_no_project_context():
    assert rubric.forbidden_hits(PROBE_PROMPT.format(path="C:/tmp/probe.mp4")) == []
    for mv in MOVEMENTS:
        assert rubric.forbidden_hits(f'The robot says: "{mv.text}"') == []
        assert rubric.forbidden_hits(f"The robot expresses: {mv.expression}") == []


def test_forbidden_hits_is_case_insensitive():
    hits = set(rubric.forbidden_hits("This Vendor clip was GENERATED by a Model"))
    assert {"model", "generated", "vendor"} <= hits
    assert rubric.forbidden_hits("The robot nods twice and settles.") == []


# ---------------------------------------------------------------- workspace hygiene
def test_manifest_never_enters_the_workspace(tmp_path):
    run_dir = tmp_path / "run"
    run_dir.mkdir()
    (run_dir / "manifest_sealed.json").write_text('{"secret": true}', encoding="utf-8")
    reel = run_dir / "lamp_reel1.mp4"
    reel.write_bytes(b"\x00\x00\x00\x18ftypmp42")
    ws = tmp_path / "ws" / "lamp_reel1"
    ws.mkdir(parents=True)
    (ws / "leftover.txt").write_text("stale", encoding="utf-8")   # anything already there must go
    dst = prepare_workspace(str(reel), ws)
    assert dst.name == "lamp_reel1.mp4"
    listing = check_workspace(ws)
    assert listing == ["lamp_reel1.mp4"]
    assert kimi.workspace_listing(ws) == ["lamp_reel1.mp4"]
    assert not any("manifest" in f for f in listing)
    # a manifest (or any json / results file) inside the workspace is a hard error
    (ws / "manifest_sealed.json").write_text("{}", encoding="utf-8")
    with pytest.raises(RuntimeError):
        check_workspace(ws)


def test_judge_workspace_path_carries_no_project_context():
    root = judge_workspace_root("20260826_2320")
    assert rubric.forbidden_hits(str(root)) == []
    assert "motion_judge" in str(root)
    # the reel path is quoted in the prompt, so it is checked with everything else
    prompt = rubric.build_prompt(str(root / "lamp_reel1" / "lamp_reel1.mp4"), [1, 2], "lamp")
    assert rubric.forbidden_hits(prompt) == []


# ---------------------------------------------------------------- reels
def _fake_clip(robot, mv, source, seed, seconds=3.0):
    n = int(seconds * 30) + 1
    prof = find_robot(robot)
    table = pd.DataFrame({"t": np.arange(n) / 30.0, **{j.name: np.full(n, j.rest) for j in prof.joints}})
    return ClipSpec(id=f"{robot}/{mv}/{source}/s{seed}", robot=robot, movement=mv, source=source, seed=seed,
                    card_line="x", table=table, audio=np.zeros(int(seconds * 16000), np.float32))


def _fake_clips(robot="lamp", seeds=2, sources=("model", "retrieval", "envelope")):
    out = []
    for mv in MOVEMENT_KEYS:
        for s in sources:
            for k in range(seeds):
                out.append(_fake_clip(robot, mv, s, k))
        out.append(_fake_clip(robot, mv, VENDOR, None, seconds=4.0))
    return out


def test_reel_order_is_seeded_and_numbers_are_a_permutation():
    clips = _fake_clips()
    a = number_and_shuffle(clips, 0)
    b = number_and_shuffle(clips, 0)
    c = number_and_shuffle(clips, 1)
    assert [e.clip.id for e in a] == [e.clip.id for e in b]
    assert [e.clip.id for e in a] != [e.clip.id for e in c]
    assert [e.number for e in a] == list(range(1, len(clips) + 1))
    assert [e.clip.id for e in a] != [c_.id for c_ in clips], "shuffle must change the order"
    assert sorted(e.clip.id for e in a) == sorted(c_.id for c_ in clips)


def test_reels_are_consecutive_and_under_the_limit():
    numbered = number_and_shuffle(_fake_clips(), 3)
    reels = chunk_reels(numbered, "lamp", max_seconds=60)
    assert len(reels) >= 2
    seen = []
    for r in reels:
        assert r.numbers == list(range(r.numbers[0], r.numbers[-1] + 1))
        assert r.seconds <= 60 * 1.05
        seen.extend(r.numbers)
    assert seen == list(range(1, len(numbered) + 1))


def test_sealed_manifest_maps_every_number_to_its_origin():
    clips = _fake_clips("lamp") + _fake_clips("reachy_mini")
    plans = plan_reels(clips, seed=7, max_seconds=90)
    m = sealed_manifest(plans, 7)
    assert set(m["robots"]) == {"lamp", "reachy_mini"}
    for robot, entry in m["robots"].items():
        ids = {v["id"] for v in entry["clips"].values()}
        assert ids == {c.id for c in clips if c.robot == robot}
        for v in entry["clips"].values():
            assert v["source"] in {"model", "retrieval", "envelope", VENDOR}
            assert v["movement"] in MOVEMENT_KEYS
    json.dumps(m)  # serialisable


# ---------------------------------------------------------------- JSON robustness
def test_extract_json_is_robust_to_prose_fences_and_junk():
    good = {"clips": [{"clip": 1, "scores": {"overall": 7}}], "notes": "n"}
    text = "Sure! Here is my review:\n```json\n" + json.dumps(good) + "\n```\nHope this helps { not json"
    assert kimi.extract_json(text) == good
    text2 = "{ broken { " + json.dumps(good)
    assert kimi.extract_json(text2) == good
    with pytest.raises(kimi.KimiError):
        kimi.extract_json("no json here at all")


def test_parse_stream_json_collects_assistant_text():
    lines = [json.dumps({"role": "assistant", "content": "part one "}), "garbage line",
             json.dumps({"role": "meta", "content": "ignored"}), json.dumps({"role": "assistant", "content": '{"a": 1}'})]
    assert kimi.extract_json(kimi.parse_stream_json("\n".join(lines))) == {"a": 1}


def test_validate_response_catches_missing_duplicate_and_out_of_range():
    ok = {"clips": [{"clip": n, "description": "moves", "scores": {k: 7 for k in rubric.SCORE_KEYS}} for n in (1, 2, 3)]}
    assert rubric.validate_response(ok, [1, 2, 3]) == []
    missing = {"clips": ok["clips"][:2]}
    assert any("missing" in e for e in rubric.validate_response(missing, [1, 2, 3]))
    dup = {"clips": ok["clips"] + [ok["clips"][0]]}
    assert any("twice" in e for e in rubric.validate_response(dup, [1, 2, 3]))
    bad = json.loads(json.dumps(ok))
    bad["clips"][1]["scores"]["overall"] = 11
    assert any("out of range" in e for e in rubric.validate_response(bad, [1, 2, 3]))
    nodesc = json.loads(json.dumps(ok))
    nodesc["clips"][0]["description"] = ""
    assert any("no description" in e for e in rubric.validate_response(nodesc, [1, 2, 3]))
    assert rubric.validate_response({"nope": 1}, [1]) == ["no 'clips' list"]


# ---------------------------------------------------------------- the gate
def _records(robot, model_scores, vendor_scores=(8, 8, 8, 8, 8), retrieval=None):
    recs = []
    for mv, seeds in zip(MOVEMENT_KEYS, model_scores):
        for k, v in enumerate(seeds):
            recs.append({"robot": robot, "movement": mv, "source": "model", "seed": k, "overall": v, "scores": {"overall": v}})
    for mv, v in zip(MOVEMENT_KEYS, vendor_scores):
        recs.append({"robot": robot, "movement": mv, "source": VENDOR, "seed": None, "overall": v, "scores": {"overall": v}})
    for mv, seeds in (retrieval or {}).items():
        for k, v in enumerate(seeds):
            recs.append({"robot": robot, "movement": mv, "source": "retrieval", "seed": k, "overall": v, "scores": {"overall": v}})
    return recs


def test_gate_passes_only_when_every_movement_mean_reaches_the_threshold():
    assert GATE_THRESHOLD == 8.0
    g = gate(_records("lamp", [(8, 8), (9, 8), (8, 9), (10, 8), (8, 8)]), "lamp")
    assert g["pass"] is True
    assert all(g["per_movement"][mv]["pass"] for mv in MOVEMENT_KEYS)
    # exactly on the line passes; one tenth below fails
    assert gate(_records("lamp", [(8, 8)] * 5), "lamp")["pass"] is True
    assert gate(_records("lamp", [(8, 8)] * 4 + [(7, 8)]), "lamp")["pass"] is False


def test_gate_uses_mean_over_seeds_not_best_of_seeds():
    g = gate(_records("lamp", [(10, 6), (9, 9), (8, 8), (8, 9), (8, 8)]), "lamp")
    assert g["per_movement"]["greeting"]["mean"] == 8.0 and g["per_movement"]["greeting"]["pass"] is True
    g2 = gate(_records("lamp", [(9, 6), (9, 9), (8, 8), (8, 9), (8, 8)]), "lamp")
    assert g2["per_movement"]["greeting"]["mean"] == 7.5
    assert g2["pass"] is False
    assert g2["best_of_seeds_would_pass"] is True, "best-of-seeds is reported but must not decide"


def test_gate_fails_when_a_movement_is_missing_or_unscored():
    recs = _records("lamp", [(9, 9), (9, 9), (9, 9), (9, 9), (9, 9)])
    recs = [r for r in recs if not (r["source"] == "model" and r["movement"] == "thinking")]
    g = gate(recs, "lamp")
    assert g["pass"] is False and g["per_movement"]["thinking"]["n"] == 0
    recs2 = _records("lamp", [(9, 9), (9, 9), (9, 9), (9, 9), (9, None)])
    g2 = gate(recs2, "lamp")
    assert g2["per_movement"]["thinking"]["n"] == 1 and g2["pass"] is True


def test_gate_is_per_robot_and_only_looks_at_the_model_source():
    recs = _records("lamp", [(9, 9)] * 5) + _records("reachy_mini", [(5, 5)] * 5, retrieval={mv: (10, 10) for mv in MOVEMENT_KEYS})
    assert gate(recs, "lamp")["pass"] is True
    assert gate(recs, "reachy_mini")["pass"] is False, "retrieval scoring 10 must not rescue the model"


def test_calibration_flags_a_broken_rubric_or_render():
    assert CALIBRATION_MIN == 6.0
    ok = calibration(_records("lamp", [(8, 8)] * 5, vendor_scores=(7, 6, 8, 9, 6)), "lamp")
    assert ok["ok"] is True and ok["note"] is None
    bad = calibration(_records("lamp", [(8, 8)] * 5, vendor_scores=(5, 4, 6, 5, 5)), "lamp")
    assert bad["ok"] is False and "broken" in bad["note"]


def test_consistency_measures_the_gap_between_identical_retrieval_seeds():
    recs = _records("lamp", [(8, 8)] * 5, retrieval={"greeting": (7, 9), "doubt": (6, 6)})
    c = consistency(recs, "lamp")
    assert c["pairs"] == 2 and c["mean_abs_gap"] == 1.0


# ---------------------------------------------------------------- unsealing
def test_unseal_joins_blind_numbers_with_origins():
    clips = _fake_clips("lamp", seeds=1, sources=("model",))
    plans = plan_reels(clips, seed=0, max_seconds=1000)
    m = sealed_manifest(plans, 0)
    reel = plans["lamp"][0]
    answer = {"clips": [{"clip": n, "description": f"d{n}", "reason": "r",
                         "scores": {k: (9 if n % 2 else 4) for k in rubric.SCORE_KEYS}} for n in reel.numbers]}
    recs = unseal([{"reel": reel.name, "robot": "lamp", "numbers": reel.numbers, "answer": answer, "valid": True}], m)
    assert len(recs) == len(clips)
    for r in recs:
        assert r["id"] == m["robots"]["lamp"]["clips"][str(r["number"])]["id"]
        assert r["overall"] == (9 if r["number"] % 2 else 4)
        assert r["description"] == f"d{r['number']}"


# ---------------------------------------------------------------- rendering arithmetic (no browser)
def test_resample_and_urdf_frames_match_table_length():
    prof = find_robot("lamp")
    t = np.array([0.0, 0.05, 0.10, 0.15, 0.20])           # a 20 Hz vendor table
    table = pd.DataFrame({"t": t, **{j.name: j.rest + np.linspace(0, 10, 5) for j in prof.joints}})
    r = resample_table(table, 30)
    assert len(r) == 7 and abs(r["t"].iloc[-1] - 0.2) < 1e-9
    frames = urdf_frames(r, prof)
    assert len(frames) == 7 and set(frames[0]) == {j.urdf_joint for j in prof.joints}
    assert abs(frames[-1]["base_yaw"] - np.deg2rad(prof.joint("base_yaw").rest + 10)) < 1e-6


def test_most_active_window_picks_the_gesture_not_the_hold():
    from animacy.grade.movements import most_active_window

    t = np.arange(0, 12.0, 0.05)
    x = np.zeros_like(t)
    x[(t >= 5) & (t < 8)] = 30 * np.sin(2 * np.pi * 2 * t[(t >= 5) & (t < 8)])   # the gesture sits at 5..8 s
    table = pd.DataFrame({"t": t, "a": x, "b": np.zeros_like(t)})
    w = most_active_window(table, 6.0)
    assert abs(w["t"].iloc[0]) < 1e-9 and abs(w["t"].iloc[-1] - 6.0) < 0.06
    assert w["a"].abs().max() > 25, "the window must contain the gesture"
    short = most_active_window(table[table["t"] < 3.0], 6.0)
    assert len(short) == int(3.0 / 0.05)


def test_speech_envelope_is_per_frame_and_silent_when_no_audio():
    assert np.all(speech_envelope(None, 16000, 30) == 0)
    a = np.zeros(16000, np.float32)
    a[8000:] = 0.5
    env = speech_envelope(a, 16000, 30)
    assert len(env) == 30 and env[:14].max() == 0 and env[16:].min() > 0.99


def test_slow_motion_variant_stretches_time_and_audio_together():
    c = _fake_clip("lamp", "greeting", "model", 0, seconds=2.0)
    t = slow_table(c.table, 0.5)
    assert abs(t["t"].iloc[-1] - 4.0) < 1e-9 and len(t) == len(c.table)
    a = slow_audio(c.audio, 0.5)
    assert abs(len(a) / 16000 - 4.0) < 0.01
    assert slow_audio(c.audio, 1.0) is c.audio and slow_audio(None, 0.5) is None


def test_entry_level_overall_is_accepted_but_nothing_else_is_relaxed():
    dims = {k: 7 for k in rubric.DIMENSIONS}
    hoisted = {"clips": [{"clip": 1, "description": "moves", "scores": dict(dims), "overall": 8}]}
    assert rubric.validate_response(hoisted, [1]) == []
    assert rubric.normalise_scores(hoisted["clips"][0])["overall"] == 8.0
    nowhere = {"clips": [{"clip": 1, "description": "moves", "scores": dict(dims)}]}
    assert any("overall" in e for e in rubric.validate_response(nowhere, [1]))
    text = {"clips": [{"clip": 1, "description": "moves", "scores": dict(dims), "overall": "eight"}]}
    assert any("overall" in e for e in rubric.validate_response(text, [1]))


# ---------------------------------------------------------------- gate source + intent pass-through
def test_gate_source_auto_is_the_shipped_default_backend(monkeypatch, tmp_path):
    from animacy.grade import run as runmod

    (tmp_path / "web" / "models").mkdir(parents=True)
    (tmp_path / "web" / "models" / "model.json").write_text('{"default_backend": "retrieval"}', encoding="utf-8")
    monkeypatch.setattr(runmod, "ROOT", str(tmp_path))
    g = resolve_gate_source("auto", ["model", "retrieval", "envelope"])
    assert g["source"] == "retrieval" and "default_backend" in g["why"]
    assert resolve_gate_source("model", ["model", "retrieval"])["source"] == "model"
    with pytest.raises(ValueError):
        resolve_gate_source("auto", ["model", "envelope"])       # shipped default not graded -> refuse
    (tmp_path / "web" / "models" / "model.json").write_text("{}", encoding="utf-8")
    assert resolve_gate_source("auto", ["model"])["source"] == "model"


def test_summarise_gates_on_the_requested_source_and_reports_the_rest():
    recs = _records("lamp", [(5, 5)] * 5, retrieval={mv: (9, 9) for mv in MOVEMENT_KEYS})
    s = summarise(recs, ["lamp"], ["model", "retrieval"], gate_source="retrieval")
    assert s["gate_source"] == "retrieval"
    assert s["robots"]["lamp"]["gate"]["pass"] is True
    assert s["robots"]["lamp"]["gate_by_source"]["model"]["pass"] is False
    s2 = summarise(recs, ["lamp"], ["model", "retrieval"], gate_source="model")
    assert s2["robots"]["lamp"]["gate"]["pass"] is False


def test_intent_is_passed_only_to_sources_that_accept_it():
    from animacy.schema import HumanClip, empty_frames

    prof = find_robot("lamp")
    calls = {}

    def _clip():
        f = empty_frames(30)
        f["face_valid"] = 1.0
        return HumanClip.from_frames(f, source="fake")

    def old_style(wav, sr, checkpoint="x", seed=0):
        calls["old"] = dict(seed=seed)
        return _clip()

    def new_style(wav, sr, checkpoint="x", seed=0, intent=None):
        calls["new"] = dict(seed=seed, intent=intent)
        return _clip()

    assert accepts_intent(new_style) and not accepts_intent(old_style)
    wav = np.zeros(16000, np.float32)
    text = "No way, that is incredible news!"
    _, meta_old = candidate_table(prof, "model", wav, 16000, 1, "x", intent="excitement", text=text, sources={"model": old_style})
    _, meta_new = candidate_table(prof, "model", wav, 16000, 1, "x", intent="excitement", text=text, sources={"model": new_style})
    assert calls["old"] == {"seed": 1} and meta_old["intent_passed"] is None
    assert calls["new"]["seed"] == 1 and meta_new["intent_passed"] == "excitement"
    # the same object `animacy say --intent excitement` would hand the source: tag forced, punctuation counted
    from animacy.model.intent import analyse

    got, ref = calls["new"]["intent"], analyse(text, override="excitement")
    assert got.tag == "excitement" and got.overridden and abs(got.arousal - ref.arousal) < 1e-9
    assert all(mv.intent_tag for mv in MOVEMENTS)
    # the envelope heuristic never receives an intent even if a fake accepted one
    candidate_table(prof, "envelope", wav, 16000, 0, "x", intent="greeting", text="hi", sources={"envelope": lambda wav, sr, seed=0, intent=None: (calls.__setitem__("env", intent), _clip())[1]})
    assert calls["env"] is None


# ---------------------------------------------------------------- held-out lines (sealed)
def test_heldout_loader_builds_one_sealed_movement_per_intent(tmp_path):
    f = tmp_path / "h.json"
    f.write_text(json.dumps({"lines": {mv.key: f"sealed line number {i} for testing" for i, mv in enumerate(MOVEMENTS)}}),
                 encoding="utf-8")
    hs = load_heldout_movements(str(f))
    assert [h.key for h in hs] == MOVEMENT_KEYS
    assert all(h.line_set == HELDOUT_SET and h.label == f"{h.key}@heldout" and h.vendor == m.vendor for h, m in zip(hs, MOVEMENTS))
    assert load_heldout_movements(str(tmp_path / "missing.json")) == []
    bad = tmp_path / "bad.json"
    bad.write_text(json.dumps({"lines": {mv.key: mv.text for mv in MOVEMENTS}}), encoding="utf-8")   # reuses tuning lines
    with pytest.raises(ValueError):
        load_heldout_movements(str(bad))


def test_sealed_heldout_file_shares_no_phrase_with_tuning_lines():
    if not os.path.isfile(HELDOUT_PATH):
        pytest.skip("no sealed held-out file on this machine")
    hs = load_heldout_movements(HELDOUT_PATH)          # raises on any shared 3-gram, without printing the lines
    assert len(hs) == len(MOVEMENTS)
    for h in hs:
        for m in MOVEMENTS:
            assert not shared_phrases(h.text, m.text), f"held-out {h.key} shares a phrase with tuning {m.key}"
        assert h.text != m.text


def test_shared_phrases_is_a_3gram_check():
    assert shared_phrases("Hey! Good to see you again.", "so good to see you") == ["good to see", "to see you"]
    assert shared_phrases("Hey! Good to see you again.", "hey, see you soon") == []


def test_redaction_removes_sealed_lines_and_their_phrases():
    lines = ["Well, look who is back! It is lovely to have you here."]
    txt = "During 'look who is back' the head lifts; then on 'lovely to have you here' it settles; a nod follows."
    out = redact_lines(txt, lines)
    assert "look who is back" not in out and "lovely to have you" not in out
    assert "the head lifts" in out and "a nod follows" in out and "[...]" in out
    assert redact_lines("The whole line: well, look who is back! it is lovely to have you here.", lines).count("[...]") >= 1
    assert redact_lines("nothing sealed here", lines) == "nothing sealed here"
    assert redact_lines("", lines) == "" and redact_lines("x", []) == "x"


def _records_sets(robot, tuning, heldout, source="model"):
    recs = []
    for mv, seeds in zip(MOVEMENT_KEYS, tuning):
        for k, v in enumerate(seeds):
            recs.append({"robot": robot, "movement": mv, "source": source, "seed": k, "overall": v, "scores": {"overall": v},
                         "line_set": TUNING_SET})
    for mv, seeds in zip(MOVEMENT_KEYS, heldout):
        for k, v in enumerate(seeds):
            recs.append({"robot": robot, "movement": mv, "source": source, "seed": k, "overall": v, "scores": {"overall": v},
                         "line_set": HELDOUT_SET, "card_line": 'The robot says: "sealed words"'})
    for mv in MOVEMENT_KEYS:
        recs.append({"robot": robot, "movement": mv, "source": VENDOR, "seed": None, "overall": 7, "scores": {"overall": 7}})
    return recs


def test_gate_on_heldout_lines_ignores_tuning_scores_and_reports_the_gap():
    recs = _records_sets("lamp", tuning=[(9, 9)] * 5, heldout=[(6, 6)] * 5)
    assert gate(recs, "lamp", source="model", line_set=HELDOUT_SET)["pass"] is False
    assert gate(recs, "lamp", source="model", line_set=TUNING_SET)["pass"] is True
    s = summarise(recs, ["lamp"], ["model"], gate_source="model", gate_lines=HELDOUT_SET)
    assert s["gate_lines"] == HELDOUT_SET and s["robots"]["lamp"]["gate"]["pass"] is False
    assert s["robots"]["lamp"]["gate_by_set"][TUNING_SET]["pass"] is True
    assert abs(s["robots"]["lamp"]["contamination_gap"] - 3.0) < 1e-9
    assert set(s["robots"]["lamp"]["tables"]) == {TUNING_SET, HELDOUT_SET}
    assert s["robots"]["lamp"]["tables"][HELDOUT_SET]["greeting"][VENDOR]["mean"] == 7   # vendor shared by both sets
    assert contamination_gap(s["robots"]["lamp"]["tables"], "model") == 3.0
    # records without a line_set (run 1) are tuning lines
    old = [{k: v for k, v in r.items() if k != "line_set"} for r in recs if r.get("line_set") != HELDOUT_SET]
    assert summarise(old, ["lamp"], ["model"], gate_source="model", gate_lines=TUNING_SET)["line_sets"] == [TUNING_SET]
    with pytest.raises(ValueError):
        summarise(old, ["lamp"], ["model"], gate_source="model", gate_lines=HELDOUT_SET)


def test_intent_resolution_counts_without_storing_text():
    ir = intent_resolution(MOVEMENTS, [])
    assert ir["available"] and ir["tuning"]["n"] == len(MOVEMENTS) and "heldout" not in ir
    assert all(m.text not in json.dumps(ir) for m in MOVEMENTS)


def test_run_lock_refuses_a_second_live_writer_and_replaces_a_stale_one(tmp_path):
    d = str(tmp_path / "run")
    assert pid_alive(os.getpid()) and not pid_alive(2 ** 22 + 12345)
    path = acquire_run_lock(d)                       # our own pid: fine
    assert open(path, encoding="utf-8").read().split()[0] == str(os.getpid())
    acquire_run_lock(d)                              # re-entrant for the same pid
    release_run_lock(d)
    assert not os.path.exists(path)
    (tmp_path / "run" / "RUNNING.pid").write_text(f"{2 ** 22 + 12345} stale", encoding="utf-8")
    acquire_run_lock(d)                              # dead pid -> replaced
    release_run_lock(d)
    import subprocess, sys, time
    other = subprocess.Popen([sys.executable, "-c", "import time; time.sleep(30)"])
    try:
        (tmp_path / "run" / "RUNNING.pid").write_text(f"{other.pid} live", encoding="utf-8")
        with pytest.raises(RuntimeError):
            acquire_run_lock(d)
    finally:
        other.kill()
        other.wait()
    time.sleep(0.2)
    acquire_run_lock(d)                              # now dead -> replaced
    release_run_lock(d)


def test_critiques_quote_the_judge_verbatim_and_count_low_scores_by_source():
    recs = []
    for i, (src, sc, reason) in enumerate([("model", 3, "Frozen hold under an affirmative line."),
                                            ("model", 5, "Too slight to sell warmth."),
                                            ("retrieval", 7, "Reads well."),
                                            ("envelope", 4, "Understated, drifts only slightly.")]):
        recs.append({"robot": "lamp", "number": i + 1, "movement": "greeting", "source": src, "seed": 0, "overall": sc,
                     "scores": {"lifelike": sc, "timing": sc, "appeal": sc, "overall": sc}, "reason": reason, "description": "d"})
    recs.append({"robot": "lamp", "number": 9, "movement": "greeting", "source": VENDOR, "seed": None, "overall": 2,
                 "scores": {"lifelike": 2, "timing": 2, "appeal": 2, "overall": 2}, "reason": "vendor is excluded", "description": "d"})
    cr = critiques(recs, ["model", "retrieval", "envelope"])
    d = cr["dimensions"]["lifelike"]
    assert d["n_low"] == 3 and d["n"] == 4 and d["low_by_source"] == {"model": 2, "retrieval": 0, "envelope": 1}
    assert [q["score"] for q in d["quotes"]] == [3, 4, 5]                     # lowest first, sources spread
    assert d["quotes"][0]["reason"] == "Frozen hold under an affirmative line."
    assert all("vendor" not in q["reason"] for q in d["quotes"])
    assert any(w == "frozen" for w, _ in d["top_words"])


def test_variant_knob_applies_only_when_explicit_and_never_via_kwargs():
    from animacy.schema import HumanClip, empty_frames

    prof = find_robot("lamp")
    calls = {}

    def _clip():
        f = empty_frames(30)
        f["face_valid"] = 1.0
        return HumanClip.from_frames(f, source="fake")

    def explicit(wav, sr, checkpoint="x", seed=0, intent=None, proto_weight=1.0):
        calls["explicit"] = proto_weight
        return _clip()

    def swallow(wav, sr, checkpoint="x", seed=0, intent=None, **kw):
        calls["swallow"] = kw
        return _clip()

    v = parse_variant("retrieval_p0=retrieval:proto_weight=0")
    assert v.name == "retrieval_p0" and v.base == "retrieval" and v.kwargs == {"proto_weight": 0}
    wav = np.zeros(16000, np.float32)
    _, m1 = candidate_table(prof, "retrieval", wav, 16000, 0, "x", sources={"retrieval": explicit}, variant=v)
    assert calls["explicit"] == 0 and m1["variant"]["applied"] == {"proto_weight": 0} and not m1["variant"]["no_op"]
    _, m2 = candidate_table(prof, "retrieval", wav, 16000, 0, "x", sources={"retrieval": swallow}, variant=v)
    assert calls["swallow"] == {} and m2["variant"]["no_op"] is True
    with pytest.raises(ValueError):
        parse_variant("bad spec")
    with pytest.raises(ValueError):
        parse_variant("model=retrieval:proto_weight=0")        # collides with a real source name
